name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master # Actúa solo cuando se hace push a la rama master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequea el código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura SSH para conectar con la Raspberry Pi
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. Construye la aplicación
      - name: Build application
        run: |
          yarn install
          yarn build

      # 4. Sube los archivos a la Raspberry Pi
      - name: Deploy to Raspberry Pi
        run: |
          rsync -avz ./build/ santiago@192.168.1.175:/home/santiago/sensor

      # 5. Reinicia la aplicación en la Raspberry Pi (opcional)
      - name: Restart app
        run: |
          ssh santiago@192.168.1.175 "pm2 restart sensor || pm2 start /home/santiago/sensor --name sensor"
